# Change these first
owner: kayryu # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: BoolScan
    url: https://boolscan.com
  - name: BoolSwap
    url: https://boolswap.com
  - name: BOOL Apps
    url: https://apps.bool.network

  # Public RPC endpoints
  - name: Alpha Net WS endpoint
    check: "tcp-ping"
    url: "alpha-rpc-node-ws.bool.network"
  - name: Alpha Net HTTP endpoint
    check: "tcp-ping"
    url: "alpha-rpc-node-http.bool.network"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  workflowSchedule:
    uptime: "*/30 * * * *"
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: BOOL Network Status Page
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
